apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: vpa-admission-controller
  namespace: kube-system
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: vpa-admission-controller
