apiVersion: v1
kind: Service
metadata:
  name: http-api
  namespace: default
  labels:
    app: http-api
spec:
  ports:
  - port: 80
    targetPort: http
    name: http
  selector:
    app: http-api
  type: LoadBalancer

